# chronicle-[alpha/beta/etc.]-v[x.x.x].[ext]
[version]
version = "chronicle-alpha-v0.1.0"
service = "Permanode"

# More details: https://docs.scylladb.com/getting-started/ddl/
[scylla_cluster]
addresses = ["172.17.0.2:9042"] # scylla docker instance
keyspace_name = "tangle"
replication_factor_per_data_center = 1
data_centers = ["datacenter1"]
local_dc = "datacenter1"

# dmp file links: https://dbfiles.iota.org/?prefix=mainnet/history/
# [[file_path1, milestone1], [file_path2, milestone2], ...]
[dmp_files]
files = []

[tokio]
core_threads = 4 # should use even number > 2

[storage]
dashboard_websocket = "0.0.0.0:8080"

[api]
endpoint = "0.0.0.0:4000"

[broker]
trytes_nodes = ["tcp://zmq.iota.org:5556"]
sn_trytes_nodes = ["tcp://zmq.iota.org:5556"]
