# chronicle-[alpha/beta/etc.]-v[x.x.x].[ext]
[version]
version = "chronicle-alpha-v0.1.0"
service = "Permanode"

# logger settings
[logger]
color = true
[[logger.outputs]]
name  = "stdout"
level = "info"

# More details: https://docs.scylladb.com/getting-started/ddl/
[scylla_cluster]
addresses = ["172.17.0.2:9042"] # scylla docker instance
replication_factor_per_data_center = 1
data_centers = ["datacenter1"]
local_dc = "datacenter1"

# dmp file links: https://dbfiles.iota.org/?prefix=mainnet/history/
# [[file_path1, milestone1], [file_path2, milestone2], ...]
[dmp_files]
files = []
import_only_confirmed_transactions = true
max_retries = 1000

[tokio]
core_threads = 2 # should use even number > 2

[storage]
dashboard_websocket = "0.0.0.0:8080"

[api]
endpoint = "0.0.0.0:4000"
content_length = 65535

[broker]
trytes_nodes = ["tcp://hornetdev01.mainnet.iota.cafe:1883"]
conf_trytes_nodes = []
max_retries = 100
